/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-05-07 01:18:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("    <title>系统登录</title>\r\n");
      out.write("    <link href=\"/static/styles/learun-login.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"/static/styles/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!–[if lt IE 9]><script src=\"/static/scripts/html5/json2.js\"></script><![endif]–>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        body {\r\n");
      out.write("            background: url(/static/images/login-bgm.jpg) no-repeat fixed center;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("        }\r\n");
      out.write("        .clearfix:after{\r\n");
      out.write("            display: block;\r\n");
      out.write("            content: '';\r\n");
      out.write("            clear: both;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"aaabody\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("    <div style=\"text-align: center;\">\r\n");
      out.write("        <img src=\"/static/images/on-line.png\" style=\"border-radius: 96px; margin-bottom: -48px;\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"loginform\" class=\"container\">\r\n");
      out.write("        <fieldset class=\"box\">\r\n");
      out.write("            <legend>城市供水管网漏损评估与分析系统</legend>\r\n");
      out.write("            <dl class=\"form\">\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <input id=\"username\" type=\"text\" class=\"px\" placeholder=\"请输入用户名\">\r\n");
      out.write("                </dd>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <input id=\"password\" type=\"password\" class=\"px\" placeholder=\"请输入用户密码\">\r\n");
      out.write("                </dd>\r\n");
      out.write("                <dd class=\"clearfix\" style=\"margin: 0\">\r\n");
      out.write("                    <div style=\"float:right;padding-right:10%;\">\r\n");
      out.write("                        <div style=\"float: left;margin-top:3px;margin-right:2px;\">\r\n");
      out.write("                            <font>记住密码</font>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"float: left;\">\r\n");
      out.write("                            <input name=\"form-field-checkbox\" id=\"saveid\" type=\"checkbox\" onclick=\"savePaw();\" style=\"padding-top:0;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </dd>\r\n");
      out.write("                <dd class=\"btn\">\r\n");
      out.write("                    <button id=\"btnlogin\" type=\"button\" class=\"pn\"><span>登录</span></button>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"copyright\" style=\"color: #fff;\">\r\n");
      out.write("    上海桑锐电子科技股份有限公司\r\n");
      out.write("    <br>\r\n");
      out.write("    官方网站：http://www.51sunray.com\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/static/scripts/jquery/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/plugins/jquery.md5.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/plugins/cookie/jquery.cookie.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/plugins/dialog/dialog.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/utils/learun-ui.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/plugins/validator/validator.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/plugins/tipso.min.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/plugins/cryptojs/crypto-js.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/plugins/biginteger/BigInteger.js\"></script>\r\n");
      out.write("<script src=\"/static/scripts/utils/encrypt.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    var isIE = !!window.ActiveXObject;\r\n");
      out.write("    var isIE6 = isIE && !window.XMLHttpRequest;\r\n");
      out.write("    if (isIE6) {\r\n");
      out.write("        window.location.href = \"/error/errorBrowser\";\r\n");
      out.write("    }\r\n");
      out.write("    //回车键\r\n");
      out.write("    $('#loginform').on('keydown', function (e) {\r\n");
      out.write("        if(e.keyCode === 13){\r\n");
      out.write("            $('#btnlogin').trigger('click')\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //初始化\r\n");
      out.write("    $(function () {\r\n");
      out.write("\r\n");
      out.write("        var username = $.cookie('username');\r\n");
      out.write("        var password = $.cookie('password');\r\n");
      out.write("        if (typeof username !== \"undefined\" && typeof password !== \"undefined\") {\r\n");
      out.write("            $(\"#username\").val(username);\r\n");
      out.write("            $(\"#password\").val(password);\r\n");
      out.write("            $(\"#saveid\").attr(\"checked\", true);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\".wrap\").css(\"margin-top\", ($(window).height() - $(\".wrap\").height()) / 2 - 35);\r\n");
      out.write("        $(window).resize(function (e) {\r\n");
      out.write("            $(\".wrap\").css(\"margin-top\", ($(window).height() - $(\".wrap\").height()) / 2 - 35);\r\n");
      out.write("            e.stopPropagation();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        //登录按钮事件\r\n");
      out.write("        $(\"#btnlogin\").click(function () {\r\n");
      out.write("            var $username = $(\"#username\");\r\n");
      out.write("            var $password = $(\"#password\");\r\n");
      out.write("            if ($username.val() === \"\") {\r\n");
      out.write("                $username.focus();\r\n");
      out.write("                formMessage('请输入用户名。');\r\n");
      out.write("                return false;\r\n");
      out.write("            } else if ($password.val() === \"\") {\r\n");
      out.write("                $password.focus();\r\n");
      out.write("                formMessage('请输入密码。');\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                CheckLogin();\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    });\r\n");
      out.write("    //登录验证\r\n");
      out.write("    function CheckLogin() {\r\n");
      out.write("        $(\"#btnlogin\").addClass('active').attr('disabled', 'disabled');\r\n");
      out.write("        $(\"#btnlogin\").find('span').hide();\r\n");
      out.write("\r\n");
      out.write("        var username = $.trim($(\"#username\").val());\r\n");
      out.write("        var password = $.trim($(\"#password\").val());\r\n");
      out.write("        // password = $.md5(password);\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"/login_login\",\r\n");
      out.write("            data: { KEYDATA : username + ',fh,' + password },  //Encrypt({ KEYDATA : username + ',fh,' + password })\r\n");
      out.write("            type: \"post\",\r\n");
      out.write("            dataType: \"json\",\r\n");
      out.write("            success: function (data) {\r\n");
      out.write("\r\n");
      out.write("                /*\r\n");
      out.write("                * {\"result\":\"errInfo\"}\r\n");
      out.write("                * errInfo = \"usererror\";    // 用户名或密码有误\r\n");
      out.write("                * errInfo = \"error\";        // 缺少参数\r\n");
      out.write("                * errInfo = \"success\";      // 验证成功\r\n");
      out.write("                * */\r\n");
      out.write("\r\n");
      out.write("                if(data.result === 'usererror'){\r\n");
      out.write("                    dialogAlert('用户名或密码有误', 0);\r\n");
      out.write("                    $(\"#btnlogin\").removeClass('active').removeAttr('disabled');\r\n");
      out.write("                    $(\"#btnlogin\").find('span').show();\r\n");
      out.write("                }else if(data.result === 'error'){\r\n");
      out.write("                    dialogAlert('缺少参数', 0);\r\n");
      out.write("                    $(\"#btnlogin\").removeClass('active').removeAttr('disabled');\r\n");
      out.write("                    $(\"#btnlogin\").find('span').show();\r\n");
      out.write("                }else if(data.result === 'success'){\r\n");
      out.write("                    saveCookie();\r\n");
      out.write("                    window.location.href = '/main/index'\r\n");
      out.write("                }else{\r\n");
      out.write("                    dialogAlert('未知错误', 0);\r\n");
      out.write("                    $(\"#btnlogin\").removeClass('active').removeAttr('disabled');\r\n");
      out.write("                    $(\"#btnlogin\").find('span').show();\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function (err) {\r\n");
      out.write("                dialogAlert('登录失败', 0);\r\n");
      out.write("                $(\"#btnlogin\").removeClass('active').removeAttr('disabled');\r\n");
      out.write("                $(\"#btnlogin\").find('span').show();\r\n");
      out.write("                console.log(err)\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    //提示信息\r\n");
      out.write("    function formMessage(msg, type) {\r\n");
      out.write("        $('.login_tips').parents('dt').remove();\r\n");
      out.write("        var _class = \"login_tips\";\r\n");
      out.write("        if (type === 1) {\r\n");
      out.write("            _class = \"login_tips-succeed\";\r\n");
      out.write("        }\r\n");
      out.write("        $('.form').prepend('<dt><div class=\"' + _class + '\"><i class=\"fa fa-question-circle\"></i>' + msg + '</div></dt>');\r\n");
      out.write("    }\r\n");
      out.write("    //选中checkbox事件\r\n");
      out.write("    function savePaw() {\r\n");
      out.write("        if (!$(\"#saveid\").attr(\"checked\")) {\r\n");
      out.write("            $(\"#saveid\").attr(\"checked\", true);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    //保存密码\r\n");
      out.write("    function saveCookie() {\r\n");
      out.write("        if ($(\"#saveid\").attr(\"checked\")) {\r\n");
      out.write("            $.cookie('username', $.trim($(\"#username\").val()),{\r\n");
      out.write("                path: \"/\", expires: 7\r\n");
      out.write("            });\r\n");
      out.write("            $.cookie('password', $.trim($(\"#password\").val()),{\r\n");
      out.write("                path: \"/\", expires: 7\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
